[package]
name = "authorization_service"
version = "0.1.0"
authors = ["Greg Wiley <gwiley@cj.com>"]
edition = "2018"

[dependencies]
juniper = "0.11"
juniper-from-schema = "0.1.1"
lambda_runtime = "0.1"
serde = "^1"
serde_derive = "^1"
serde_json = "^1"
log = "^0.4"
simple_logger = "^1"
